Translation:
  - changed-files:
    - any-glob-to-any-file: 'src/main/resources/messages_*_*.properties'
    - any-glob-to-any-file: 'scripts/ignore_translation.toml'
    - any-glob-to-any-file: 'src/main/resources/templates/fragments/languages.html'

Front End:
  - changed-files:
    - any-glob-to-any-file: 'src/main/resources/templates/**/*'
    - any-glob-to-any-file: 'src/main/resources/static/**/*'
    - any-glob-to-any-file: 'src/main/java/Dockit/software/SPDF/controller/web/**'

Java:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/**/*.java'

Back End:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/Dockit/software/SPDF/config/security/**/*'
    - any-glob-to-any-file: 'src/main/java/Dockit/software/SPDF/config/model/provider/**/*'
    - any-glob-to-any-file: 'src/main/resources/settings.yml.template'
    - any-glob-to-any-file: 'src/main/resources/banner.txt'

Security:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/Dockit/software/SPDF/config/security/**/*'
    - any-glob-to-any-file: 'src/main/java/Dockit/software/SPDF/config/model/provider/**/*'
    - any-glob-to-any-file: 'src/main/java/Dockit/software/SPDF/config/model/AuthenticationType.java'

API:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/Dockit/software/SPDF/controller/web/MetricsController.java'
    - any-glob-to-any-file: 'src/main/java/Dockit/software/SPDF/controller/api/**/*'

Documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    - any-glob-to-any-file: 'scripts/counter_translation.py'
    - any-glob-to-any-file: 'scripts/ignore_translation.toml'

Docker:
  - changed-files:
    - any-glob-to-any-file: 'Dockerfile'
    - any-glob-to-any-file: 'Dockerfile-*'
    - any-glob-to-any-file: 'exampleYmlFiles/*.yml'

Test:
  - changed-files:
    - any-glob-to-any-file: 'cucumber/**/*'
    - any-glob-to-any-file: 'src/test**/*'

Github:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
