name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    

    - uses: gradle/gradle-build-action@v2.3.3
      with:
        gradle-version: 7.6
        arguments: clean build

    - name: versionNumber
      uses: gradle/gradle-build-action@v2.3.3
      with:
        gradle-version: 7.6
        arguments: printVersion -q

    
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag frooodle/s-pdf:${{ steps.versionNumber.outputs.stdout }}
 

