name: Push Docker Image with VersionNumber

on:
  push:
    branches: 
      - master
      - main
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    

    - uses: gradle/gradle-build-action@v2.3.3
      with:
        gradle-version: 7.6
        arguments: clean build

    - name: Make Gradle wrapper executable
      run: chmod +x gradlew
      
    - name: Get version number
      id: versionNumber
      run: echo "::set-output name=versionNumber::$(./gradlew printVersion --quiet | tail -1)"
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_API }} 
        
 
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          frooodle/s-pdf:${{ steps.versionNumber.outputs.versionNumber }}

    - name: Build and push
      uses: docker/build-push-action@v3
      if: github.ref == 'refs/heads/master' 
      with:
        context: .
        push: true
        tags: |
          frooodle/s-pdf:${{ steps.versionNumber.outputs.versionNumber }}


