name: Check PyMuPDF Version & Build docker image

on:
  push:
    paths:
      - '.pymupdf'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Read current version
        id: pymupdf_version
        run: |
          current_version=$(cat .pymupdf | tail -n +1 | head -n 1)
          echo "Current version: $current_version"
          echo "versionNumber=$current_version" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_API }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Convert repository owner to lowercase
        id: repoowner
        run: echo "lowercase=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT

      - name: Generate tags PyMuPDF
        id: metamu
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/pymupdf
            ghcr.io/${{ steps.repoowner.outputs.lowercase }}/pymupdf
          tags: |
            type=raw,value=${{ steps.pymupdf_version.outputs.versionNumber }},enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build PyMuPDF and push main Dockerfile
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-PyMuPDF
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.metamu.outputs.tags }}
          labels: ${{ steps.metamu.outputs.labels }}
          build-args: PYMUPDF_VERSION=${{ steps.pymupdf_version.outputs.versionNumber }}
          platforms: linux/amd64,linux/arm64/v8
